name: Firebase Test Lab

on:
  push:
    branches:
      - main  # Adjust branch, as necessary
  pull_request:
    branches:
      - main  # Adjust branch, as necessary

jobs:
  firebase-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt' # Or use 'zulu', 'oracle', 'temurin', etc.

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Create gcloud credentials file
      env:
        CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
        REFRESH_TOKEN: ${{ secrets.OAUTH_REFRESH_TOKEN }}
      run: |
        echo '{
          "client_id": "'"${CLIENT_ID}"'",
          "client_secret": "'"${CLIENT_SECRET}"'",
          "refresh_token": "'"${REFRESH_TOKEN}"'",
          "type": "authorized_user"
        }' > ${HOME}/gcloud-credentials.json
        cat ${HOME}/gcloud-credentials.json # Debug step to ensure file creation
        ls -la ${HOME}/gcloud-credentials.json # Debug step to ensure file exists
        echo "GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcloud-credentials.json" >> $GITHUB_ENV

    - name: Build the App APK
      working-directory: unit/BasicUnitAndroidTest
      run: ./gradlew assembleDebug

    - name: Build the Test APK
      working-directory: unit/BasicUnitAndroidTest
      run: ./gradlew assembleAndroidTest

    - name: Run tests in Firebase Test Lab
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${HOME}/gcloud-credentials.json
      run: |
        gcloud auth activate-refresh-token zhaomingyin@google.com ${{ secrets.OAUTH_REFRESH_TOKEN }}
        GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcloud-credentials.json gcloud firebase test android run \
          --type instrumentation \
          --app app/build/outputs/apk/debug/app-debug.apk \
          --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
          model=seahawk,version=33,locale=en_US,orientation=portrait
